// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the prompt needs to know about a shared artifact. For files,
 * `detail` is the path that gets snapshotted.
 */
export type ArtifactRef = { kind: string, label: string, detail: string, };
