// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtifactCandidate = { 
/**
 * Stable id within the suggestion set, e.g. "a-claude".
 */
id: string, 
/**
 * Picker kind: "file" | "ai_agent" | "window" | "custom".
 */
kind: string, 
/**
 * 2-3 char icon badge, e.g. "CC", "YML".
 */
badge: string, label: string, detail: string, 
/**
 * Shows the caution marker in the picker (e.g. path may hold secrets).
 */
warn: boolean, 
/**
 * App icon as a `data:image/png;base64,...` URI; None means the UI
 * shows a placeholder badge.
 */
icon: string | null, 
/**
 * Process id of the detected session/agent; None for paths and
 * installed-only entries.
 */
pid: number | null, };
