// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactCandidate } from "./ArtifactCandidate";

export type ArtifactGroup = { 
/**
 * "Files" | "AI agents" | "Windows"
 */
title: string, items: Array<ArtifactCandidate>, };
