// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtifactCandidate = { 
/**
 * Stable id within the suggestion set, e.g. "t1", "f2".
 */
id: string, 
/**
 * Picker kind: "terminal" | "file" | "ai_agent" | "custom".
 */
kind: string, 
/**
 * 2-3 char icon badge, e.g. "iT", "YML", "CC".
 */
badge: string, label: string, detail: string, 
/**
 * Shows the amber caution marker in the picker (e.g. path may hold secrets).
 */
warn: boolean, };
