// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistStatus } from "./AssistStatus";
import type { Category } from "./Category";

export type AssistSummary = { ref: string, title: string, status: AssistStatus, category: Category | null, tags: Array<string>, 
/**
 * "Anonymous" when the assist is flagged anonymous and the viewer is not the owner.
 */
owner_name: string, 
/**
 * Responder NAMES, never a count (project plan section 11.6).
 */
responder_names: Array<string>, created_at: string, is_mine: boolean, };
