// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An artifact the owner selected or added when opening the assist.
 */
export type AssistArtifact = { id: string, 
/**
 * "terminal" | "file" | "ai_agent" | "custom"
 */
kind: string, label: string, detail: string, };
