// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An artifact the owner selected or added when opening the assist.
 */
export type AssistArtifact = { id: string, 
/**
 * "file" | "ai_agent" | "custom"
 */
kind: string, label: string, detail: string, 
/**
 * App icon as a data:image/png;base64 URI, when the scan resolved one.
 */
icon: string | null, 
/**
 * Process id at share time, for sessions and agents.
 */
pid: number | null, };
