// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BriefDraft = { 
/**
 * Short markdown bullets on what the owner intends and what the
 * artifacts show. Empty means N/A in the UI.
 */
insights: string, environment: Array<string>, };
