// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Draft produced by the Cohort AI integration. Without an API key both
 * fields stay empty - nothing is invented; the UI shows Insights as N/A.
 */
export type BriefDraft = { 
/**
 * Short markdown bullets on what the owner intends and what the
 * artifacts show.
 */
insights: string, environment: Array<string>, };
