// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistArtifact } from "./AssistArtifact";

/**
 * Owner-published snapshot of what their engine currently sees (running
 * agents and windows, suggested paths), for the responder's request wizard.
 */
export type CatalogUpload = { items: Array<AssistArtifact>, };
