// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Outcome } from "./Outcome";
import type { RecordFields } from "./RecordFields";

export type CloseAssist = { outcome: Outcome, credited_user_ids: Array<string>, record: RecordFields, };
