// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeKind } from "./ScopeKind";

export type CreateScopeRequest = { kind: ScopeKind, target: string | null, reason: string, ttl_minutes: number | null, };
