// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Outcome } from "./Outcome";

export type CreditRow = { assist_ref: string, title: string, outcome: Outcome | null, from_owner_name: string, created_at: string, };
