// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of an approve decision. For ssh requests the owner supplies the
 * connection target (user@host) here.
 */
export type DecideScopeRequest = { target: string | null, };
