// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefDraft } from "./BriefDraft";

export type DraftOutcome = { draft: BriefDraft, 
/**
 * Why the draft is empty, when it is for a reason worth showing.
 */
note: string | null, 
/**
 * The model the server reports having used.
 */
model: string | null, input_tokens: number, output_tokens: number, };
