// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistArtifact } from "./AssistArtifact";

export type DraftBriefRequest = { title: string, 
/**
 * Owner-written problem statement, source material for the analysis.
 */
description: string, artifacts: Array<AssistArtifact>, };
