// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One event for the current user, derived from the hub's tables on read.
 */
export type HubNotification = { 
/**
 * Synthetic, stable per event (e.g. "req-12-decided").
 */
id: string, 
/**
 * "scope_requested" | "scope_decided" | "comment" | "responder_joined" | "credited"
 */
kind: string, assist_ref: string, assist_title: string, actor_name: string, message: string, at: string, };
