// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactRef } from "./ArtifactRef";

export type InsightsInput = { title: string, 
/**
 * The owner's own words: the source material for the analysis.
 */
description: string, artifacts: Array<ArtifactRef>, };
