// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Protocol } from "./Protocol";

/**
 * What a machine needs to reach its model. Stored per user by the app;
 * the per-call knobs live in [`CallOptions`] instead.
 */
export type LlmConfig = { protocol: Protocol, 
/**
 * `https://api.openai.com/v1`, `http://localhost:11434/v1`,
 * `http://10.0.0.7:8000/v1`, `https://api.anthropic.com`, ...
 */
base_url: string, 
/**
 * None for local servers that take no key.
 */
api_key: string | null, model: string, };
