// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HubNotification } from "./HubNotification";

export type NotificationsResponse = { 
/**
 * Pass back as `since` on the next poll.
 */
now: string, notifications: Array<HubNotification>, };
