// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Protocol } from "./Protocol";

/**
 * A named starting point for the settings form. Picking one fills the
 * fields; the user can change any of them. Default models are set only
 * where they are known for certain - the form asks for the rest.
 */
export type Preset = { id: string, name: string, protocol: Protocol, base_url: string, default_model: string, needs_key: boolean, };
