// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordFields = { symptom: string, env_fingerprint: string, scopes_that_mattered: string, dead_ends: string, fix: string, };
