// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Outcome } from "./Outcome";

export type ResolutionRecord = { assist_ref: string, outcome: Outcome, symptom: string, env_fingerprint: string, scopes_that_mattered: string, dead_ends: string, fix: string, created_at: string, };
