// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeKind } from "./ScopeKind";
import type { ScopeStatus } from "./ScopeStatus";

export type ScopeRequest = { id: number, assist_ref: string, requester_id: string, requester_name: string, kind: ScopeKind, target: string | null, reason: string, status: ScopeStatus, 
/**
 * Request payload, e.g. the responder's SSH public key on ssh requests.
 */
payload: string | null, ttl_minutes: number | null, created_at: string, decided_at: string | null, };
