// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiAgentUsage = { name: string, model: string, share_pct: number, tokens: string, spend: string, };
