// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiAgentUsage } from "./AiAgentUsage";

export type AiUsageRange = { 
/**
 * "7d" | "30d" | "90d"
 */
range: string, tokens: string, spend: string, longest_stall: string, agents: Array<AiAgentUsage>, };
