// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Failure } from "./Failure";

export type BriefDraft = { goal: string, failures: Array<Failure>, environment: Array<string>, };
