// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistArtifact } from "./AssistArtifact";
import type { Category } from "./Category";
import type { Failure } from "./Failure";

export type CreateAssist = { title: string, tags: Array<string>, category: Category | null, anonymous: boolean, goal: string, failures: Array<Failure>, environment: Array<string>, artifacts: Array<AssistArtifact>, };
