// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One failing command or error in the brief.
 */
export type Failure = { label: string, note: string, };
