// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeKind } from "./ScopeKind";

/**
 * A live grant, derived from an approved, unexpired scope request.
 */
export type Grant = { scope_request_id: number, kind: ScopeKind, target: string | null, granted_to_id: string, granted_to_name: string, 
/**
 * None = until the assist closes.
 */
expires_at: string | null, };
