// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMsg } from "./ChatMsg";
import type { FileNode } from "./FileNode";

export type LiveData = { file_tree: Array<FileNode>, files: { [key in string]?: string }, terminal_tabs: Array<string>, terminal_feed: Array<string>, agent_chat: Array<ChatMsg>, };
