// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistStatus } from "./AssistStatus";
import type { Outcome } from "./Outcome";

/**
 * One row in "My assists" on the record screen. Owned and responded assists
 * both appear; `responder_names` on an owned row is inbound help shown as
 * names per assist - the only form inbound help ever takes.
 */
export type MyAssistRow = { ref: string, title: string, status: AssistStatus, 
/**
 * "owner" | "responder"
 */
role: string, responder_names: Array<string>, outcome: Outcome | null, created_at: string, };
