// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiUsageRange } from "./AiUsageRange";
import type { CreditRow } from "./CreditRow";
import type { MyAssistRow } from "./MyAssistRow";
import type { User } from "./User";

/**
 * Private contribution record. Outbound help accumulates; inbound help never
 * aggregates - there is deliberately no field for it here.
 */
export type MyRecord = { user: User, credits_earned: number, responses_count: number, records_count: number, my_assists: Array<MyAssistRow>, credits_rows: Array<CreditRow>, ai_usage: Array<AiUsageRange>, };
